"""Prompting modules for Loop Invariant Generation & Fixing."""

from prompts.builder import PromptBuilder
from prompts.templates import (
    PROMPT_RQ1_1_WITH_INSTRUCTIONS,
    PROMPT_RQ1_1_WITHOUT_INSTRUCTIONS,
    PROMPT_RQ1_2_PARTIAL,
    PROMPT_RQ1_2_COMBINER,
    PROMPT_FEW_SHOT,
    PROMPT_RQ1_5_INTEGRATED,
    PROMPT_RQ2_1_REPAIR_ERROR,
    PROMPT_RQ2_2_REPAIR_COUNTEREXAMPLE,
)

__all__ = [
    "PromptBuilder",
    "PROMPT_RQ1_1_WITH_INSTRUCTIONS",
    "PROMPT_RQ1_1_WITHOUT_INSTRUCTIONS",
    "PROMPT_RQ1_2_PARTIAL",
    "PROMPT_RQ1_2_COMBINER",
    "PROMPT_FEW_SHOT",
    "PROMPT_RQ1_5_INTEGRATED",
    "PROMPT_RQ2_1_REPAIR_ERROR",
    "PROMPT_RQ2_2_REPAIR_COUNTEREXAMPLE",
]
